name = "livestore-todo-app"
compatibility_date = "2024-10-28"
main = "./src/sync/client-ws.ts"
compatibility_flags = [
  "nodejs_compat",
]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO"]